import '../../src/defaultConfiguration.test'
import '../../src/serviceManager/configuration.test'
import '../../src/serviceManager/logger.test'
import '../../src/serviceManager/createServiceManager.test'
import '../../src/middlewares/defaultErrorHandler.test'
